tukcomCD2024/ISP

backend/src/main/java/com/isp/backend/domain/member/repository/MemberRepository.java, backend/src/main/java/com/isp/backend/domain/schedule/controller/ScheduleController.java, backend/src/main/java/com/isp/backend/domain/schedule/mapper/ScheduleMapper.java, backend/src/main/java/com/isp/backend/domain/schedule/repository/ScheduleRepository.java, backend/src/main/java/com/isp/backend/domain/schedule/repository/SharedScheduleRepository.java, backend/src/main/java/com/isp/backend/domain/schedule/service/ScheduleService.java, backend/src/main/java/com/isp/backend/domain/scheduleDetail/repository/ScheduleDetailRepository.java, backend/src/main/java/com/isp/backend/global/exception/ErrorCode.java, backend/src/main/java/com/isp/backend/global/exception/member/MemberNotActivatedException.java, backend/src/main/java/com/isp/backend/global/exception/member/MemberNotFoundException.java, backend/src/main/java/com/isp/backend/global/exception/member/RefreshTokenInvalidException.java, backend/src/main/java/com/isp/backend/global/exception/schedule/ImageNotFoundException.java, backend/src/main/java/com/isp/backend/global/exception/schedule/NotYourScheduleException.java, backend/src/main/java/com/isp/backend/global/exception/schedule/ScheduleNotFoundException.java, backend/src/main/java/com/isp/backend/global/s3/BucketDir.java, backend/src/main/java/com/isp/backend/global/s3/S3Config.java, backend/src/main/java/com/isp/backend/global/s3/S3Controller.java, backend/src/main/java/com/isp/backend/global/s3/S3ImageService.java, backend/src/main/java/com/isp/backend/global/s3/S3Service.java, backend/src/main/resources/application.yml
=> feat: 스케줄관련 CRUD + S3연결  + 글로벌에러설정

.github/workflows/deploy.yml, .gitignore, backend/src/main/resources/application.yml
ex) backend/feature/ec2-restart -> dev_backend
aws 변경된 환경변수를 수정
=> fix: aws env 변경

backend/scripts/deploy.sh, backend/src/main/java/com/isp/backend/domain/member/controller/MemberController.java, backend/src/main/java/com/isp/backend/domain/receipt/controller/ReceiptController.java, backend/src/main/java/com/isp/backend/domain/schedule/controller/ScheduleController.java
ex) backend/feature/modify-api-url > dev_backend
매핑되는 url 주소의 명사를 단수에서 복수로 변경
=> fix: url mapping 복수형으로 수정

backend/src/main/java/com/isp/backend/domain/country/entity/Country.java, backend/src/main/java/com/isp/backend/domain/country/repository/CountryRepository.java, backend/src/main/java/com/isp/backend/domain/flight/controller/FlightOfferController.java, backend/src/main/java/com/isp/backend/domain/flight/dto/FlightSearchRequestDTO.java, backend/src/main/java/com/isp/backend/domain/flight/mapper/FlightOfferProcessor.java, backend/src/main/java/com/isp/backend/domain/flight/service/FlightOfferService.java, backend/src/main/java/com/isp/backend/domain/schedule/repository/ScheduleRepository.java, backend/src/main/java/com/isp/backend/domain/schedule/service/ScheduleServiceImpl.java, backend/src/main/java/com/isp/backend/global/security/AmadeusConfig.java, backend/src/main/resources/application.yml
#45 
항공편 최저가 조회 API 
(pagenation 적용을 하고 싶었는데, 해당 API에서 제공하지 않는 것 같다 - 추후 개선 방법 찾기) 
#40 
스케줄 일정 목록 조회 API
=> [Backend] feat : Amadeus API - 항공편 조회 

backend/src/main/java/com/isp/backend/domain/country/controller/CountryController.java, backend/src/main/java/com/isp/backend/domain/flight/controller/FlightOfferController.java, backend/src/main/java/com/isp/backend/domain/gpt/controller/GptController.java, backend/src/main/java/com/isp/backend/domain/member/controller/MemberController.java, backend/src/main/java/com/isp/backend/domain/schedule/controller/ScheduleController.java
- rest 하지 않은 api url을 픽스
- 전체 컨트롤러의 api url 픽스
=> fix: restful api url 픽스

backend/src/main/java/com/isp/backend/domain/gpt/config/GptConfig.java, backend/src/main/java/com/isp/backend/domain/gpt/dto/request/GptScheduleRequest.java, backend/src/main/java/com/isp/backend/domain/gpt/service/GptService.java
프롬프트에 추가된 필드
#61 
includedActivities, excludedActivities 상태 적용하여 사용자 요청 반영
=> [Backend : fix] 프롬프트 요청 추가사항 반영

backend/src/main/java/com/isp/backend/domain/gpt/config/GptConfig.java
#70 Gpt4 Temperature 값 변경
- Gpt Config Temperature 필드
=> [Backend : Hotfix] #70 Gpt4 Temperature 값 변경

backend/src/main/java/com/isp/backend/domain/flight/mapper/FlightOfferProcessor.java, backend/src/main/java/com/isp/backend/domain/flight/service/FlightOfferServiceImpl.java, backend/src/main/java/com/isp/backend/domain/hotel/controller/HotelController.java, backend/src/main/java/com/isp/backend/domain/hotel/dto/request/SearchGeocodeRequest.java, backend/src/main/java/com/isp/backend/domain/hotel/service/HotelService.java, backend/src/main/java/com/isp/backend/domain/hotel/service/HotelServiceImpl.java
#67 
편도 항공권 조회, 좌표로 호텔 조회 API 추가 
- 편도 항공권 조회 가능하도록 수정 
- 좌표로 호텔 조회 API 추가 (하지만 아마데우스 API에 저장된 호텔의 개수가 너무 적어서 변경 예정)
=> [Backend] feat : 편도 항공권 조회, 좌표로 호텔 조회 API 추가 

backend/src/main/java/com/isp/backend/domain/flight/service/FlightOfferServiceImpl.java
=> [Backend] hotfix : url children 문제 해결

backend/src/main/java/com/isp/backend/domain/schedule/entity/Schedule.java
=> hotfix : 게시물 조회 API 오류 수정 

backend/src/main/java/com/isp/backend/domain/country/entity/Country.java, backend/src/main/java/com/isp/backend/domain/schedule/entity/Schedule.java, backend/src/main/java/com/isp/backend/domain/schedule/repository/ScheduleRepository.java
checklist 엔티티 연결 설정 오류로 다른 연관 테이블 참조 오류 
checklist 엔티티 연결 설정 오류로 다른 연관 테이블 참조 오류 
- 내용을 적어주세요.
=> hotfix : repository checklist 참조 오류 해결

backend/build.gradle, backend/src/main/java/com/isp/backend/domain/gpt/config/GptConfig.java, backend/src/main/java/com/isp/backend/domain/gpt/config/WebClientConfig.java, backend/src/main/java/com/isp/backend/domain/gpt/controller/GptController.java, backend/src/main/java/com/isp/backend/domain/gpt/service/GptService.java, backend/src/main/resources/application.yml
45초 걸리는 GPT 응답 시간을 10초로 단축
- GPT 응답 시간
=> [Backend : Feat] 비동기 처리를 통한 GPT 응답 시간 단축

backend/src/main/java/com/isp/backend/domain/flight/controller/FlightOfferController.java, backend/src/main/java/com/isp/backend/domain/flight/service/FlightOfferService.java, backend/src/main/java/com/isp/backend/domain/flight/service/FlightOfferServiceImpl.java
항공권 좋아요 API 응답값 수정
항공권 좋아요 API 응답값 수정 -> id값 반환 
- 내용을 적어주세요.
=> [Backend] 항공권 좋아요 API 응답값 수정

backend/src/main/java/com/isp/backend/domain/gpt/config/GptConfig.java, backend/src/main/java/com/isp/backend/domain/gpt/config/WebClientConfig.java, backend/src/main/java/com/isp/backend/domain/gpt/constant/ParsingConstants.java, backend/src/main/java/com/isp/backend/domain/gpt/entity/GptScheduleParser.java
#95 
- 날짜와 좌표를 구분하지 못하는 문제 해결
- 내용을 적어주세요.
=> Hotfix: 좌표와 날짜를 구분하도록 파싱메서드 수정

backend/src/main/java/com/isp/backend/domain/country/controller/CountryController.java, backend/src/main/java/com/isp/backend/domain/country/dto/request/CurrencyCalculateRequest.java, backend/src/main/java/com/isp/backend/domain/country/dto/response/DailyWeatherResponse.java, backend/src/main/java/com/isp/backend/domain/country/entity/ExchangeRate.java, backend/src/main/java/com/isp/backend/domain/country/repository/ExchageRateRespository.java, backend/src/main/java/com/isp/backend/domain/country/service/CountryService.java, backend/src/main/java/com/isp/backend/domain/country/service/ExchangeRateService.java, backend/src/main/resources/application.yml
weather API METHOd 변경 
- 내용을 적어주세요.
=> fix : weather API METHOD 변경

backend/src/main/java/com/isp/backend/domain/country/service/ExchangeRateService.java
=> fix : 통화코드 오타 수정

backend/src/main/java/com/isp/backend/domain/gpt/config/GptConfig.java, backend/src/main/java/com/isp/backend/domain/gpt/entity/GptScheduleParser.java
#121 gpt 프롬프트 이슈
gpt propmt 및 파싱 메서드 수정
- 내용을 적어주세요.
=> [Backend : Fix] gpt propmt 및 파싱 메서드 수정

backend/src/main/java/com/isp/backend/domain/scheduleImage/controller/ScheduleImageController.java, backend/src/main/java/com/isp/backend/domain/scheduleImage/dto/request/SaveScheduleImageRequest.java, backend/src/main/java/com/isp/backend/domain/scheduleImage/dto/response/ReadScheduleImageResponse.java, backend/src/main/java/com/isp/backend/domain/scheduleImage/dto/response/SaveScheduleImageResponse.java, backend/src/main/java/com/isp/backend/domain/scheduleImage/entity/ScheduleImage.java, backend/src/main/java/com/isp/backend/domain/scheduleImage/repository/ScheduleImageRepository.java, backend/src/main/java/com/isp/backend/domain/scheduleImage/repository/ScheduleImageS3Repository.java, backend/src/main/java/com/isp/backend/domain/scheduleImage/service/DeleteScheduleImageService.java, backend/src/main/java/com/isp/backend/domain/scheduleImage/service/ReadScheduleImageService.java, backend/src/main/java/com/isp/backend/domain/scheduleImage/service/SaveImageService.java, backend/src/main/java/com/isp/backend/domain/scheduleImage/service/SaveScheduleImageService.java, backend/src/main/java/com/isp/backend/domain/scheduleImage/service/ScheduleImageService.java
=> 사용자가 저장한 이미지를 일정 별로 Read, Delete 하는 API 구현

backend/src/main/java/com/isp/backend/domain/receipt/dto/response/ScheduleListWithReceiptResponse.java, backend/src/main/java/com/isp/backend/domain/receipt/mapper/ReceiptMapper.java
#
Fix : 영수증용 일정 목록 API 컬럼 추가
- 내용을 적어주세요.
=> Fix : 영수증용 일정 목록 API 컬럼 추가

backend/src/main/java/com/isp/backend/domain/country/dto/response/LocationResponse.java, backend/src/main/java/com/isp/backend/domain/country/service/CountryServiceImpl.java, backend/src/main/java/com/isp/backend/domain/receipt/service/ReceiptService.java, backend/src/main/java/com/isp/backend/domain/schedule/dto/request/ScheduleSaveRequest.java, backend/src/main/java/com/isp/backend/domain/schedule/dto/response/FastestScheduleResponse.java, backend/src/main/java/com/isp/backend/domain/schedule/dto/response/LatestCreateResponse.java, backend/src/main/java/com/isp/backend/domain/schedule/mapper/ScheduleMapper.java
#139 
Schedule API CurrencyName 추가 
- 내용을 적어주세요.
=> [Backend : Fix ] Schedule API CurrencyName 추가 
